[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tauri = { version = "2.11.5", features = [] }
shared = { workspace = true }
lib = { workspace = true }

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }
