[package]
name = "shared"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time.workspace = true
jsonschema = { version = "0.56", default-features = false }

[build-dependencies]
typify = { version = "0.8", default-features = false }
schemars = "0.8"
serde_json.workspace = true
prettyplease = "0.2"
syn = { version = "2", features = ["full"] }
