[package]
name = "video"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
common.workspace = true
wgpu.workspace = true
egui.workspace = true
egui-wgpu.workspace = true
bytemuck.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
winit.workspace = true
pollster.workspace = true
tracing.workspace = true
