[package]
name = "winit-wgpu"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ab_glyph = "0.2"
anyhow = "1.0.102"
bytemuck = { version = "1", features = ["derive"] }
glam = { version = "0.29", features = ["bytemuck"] }
image = "0.25.9"
rand = "0.9"
tracing = "0.1.44"
web-time = "1"
wgpu = "22"
winit = "0.30"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "0.3"
rapier2d = { version = "0.22", features = ["simd-stable"] }
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }
rapier2d = "0.22"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Document", "Element", "HtmlCanvasElement", "Window"] }
console_error_panic_hook = "0.1"
tracing-wasm = "0.2"
wgpu = { version = "22", features = ["webgl"] }
