[package]
name = "client"
version.workspace = true
edition.workspace = true

[dependencies]
leptos = { version = "0.8.20", features = ["csr"] }
shared = { workspace = true }
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.127"
wasm-bindgen-futures = "0.4.77"
serde = { workspace = true, features = ["derive"] }
